fails:Thread#terminate can be rescued by outer rescue clause when inner ensure clause raises exception
fails:Thread#terminate is deferred if ensure clause does Thread.stop
