fails:Array.try_convert does not rescue exceptions
fails:Array.try_convert checks the result of the conversion
fails:Array.try_convert sends #to_ary to the argument and raises TypeError if it's not a kind of Array
